name: Kubescape scanning for misconfigurations
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - name: Install Kubescape
      run: |
        KUBESCAPE_DIR="$HOME/kubescape-bin"
        mkdir -p "$KUBESCAPE_DIR"
        LATEST_VERSION=$(curl -s https://api.github.com/repos/kubescape/kubescape/releases/latest | jq -r .tag_name)
        curl -sL "https://github.com/kubescape/kubescape/releases/download/${LATEST_VERSION}/kubescape-ubuntu-latest" -o "$KUBESCAPE_DIR/kubescape"
        chmod +x "$KUBESCAPE_DIR/kubescape"
        echo "$KUBESCAPE_DIR" >> $GITHUB_PATH
        
    - name: Run Kubescape scan
      run: |
        kubescape scan framework all *.yaml \
          --format sarif \
          --output results.sarif

          - name: Upload Kubescape scan results to Github Code Scanning
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: results.sarif
